### ISSUE TITLE
[Enhancement] Increase CloudWatch Metrics Coverage

### ISSUE THREAD

**Issue by philipkimmey** [buildkite/buildkite-agent-scaler#29]
Hello!

We've previously been using the native autoscaling behaviors in elastic-ci-stack and just started testing out the Lambda-based scaler for a small number of our largest queues.

As far as I can tell it's been working great, but unfortunately, the lack of published CloudWatch metrics makes it very hard to tell for sure, since in recent releases that stack only deploys the buildkite-agent-metrics lambda when `Condition: UseNativeAutoscaling` is met - and the current integration branch in that repository doesn't enable the `buildkite-agent-metrics` lambda at all.

Although the broader set of metrics isn't needed anymore to actually drive the native autoscaling capabilities, not pushing those metrics makes it very hard to have sufficient visibility into utilization rate and wait times.

Specifically, I have dashboards in CloudWatch and Datadog that rely on:

- TotalAgentCount by queue
- BusyAgentCount by queue

We could certainly spin up the other metrics lambda separately but given our use-case is pretty middle of the road, it'd be preferable to just add at least those metrics to the set of CloudWatch metrics being published. (Alternatively, you could also just add a flag in the elastic-ci-stack to also run the metrics agent.

Thank you!

**Comment by keithduncan** [comment]
Hi @philipkimmey, thank you for opening this issue. We have been discussing this use case and have chosen to renew support for the buildkite-agent-metrics Lambda instead of building more metrics in to the scaling Lambda.

We hope to make deploying the metrics Lambda even easier in the future, we aren’t sure what shape that will take but will likely include publishing a template to the AWS Serverless Application Repository. This may work its way up to a parameter of the Elastic CI Stack based on how popular it ends up being, but I can’t promise anything.

I hope having a clear path forward for getting these metrics back in to CloudWatch is beneficial and please do let us know if there’s anything missing from there that we can add support for.
